site_name: openai-cookbook  # 网站名称
site_url: https://openai.icopy.site/  # 域名
theme:
  name: material
  language: en

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

plugins:
  - mkdocs-jupyter
  - search


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      toc_depth: 3  #右侧toc显示到几级标题
      permalink: true
