name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-jupyter
      - run: cd docs && git clone https://github.com/openai/openai-cookbook.git
      - run: rm -rf docs/openai-cookbook/.git
      - run: rm -rf docs/openai-cookbook/examples/vector_databases/pinecone
      - run: cd .. && mkdocs gh-deploy --force
